services:

  openldap-app:
    hostname: ldap.example.org
    image: docker.io/nfrastack/openldap:2.6
    container_name: openldap-app
    ports:
      - 389:389
      - 636:636
    volumes:
      #- ./backup:/data/backup
      #- ./config:/data/config
      #- ./data:/data/db
      - ./data:/data
      - ./certs:/certs
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver

      - HOSTNAME=ldap.example.org
      - DOMAIN=example.org
      - BASE_DN=dc=example,dc=org

      - LOG_LEVEL=256

      - ADMIN_PASS=admin
      - CONFIG_PASS=config

      - DEBUG_MODE=FALSE

      - ENABLE_READONLY_USER=FALSE
      - READONLY_USER_USER=reader
      - READONLY_USER_PASS=reader

      - ENABLE_TLS=TRUE
      - TLS_CRT_FILENAME=cert.pem
      - TLS_KEY_FILENAME=key.pem
      - TLS_ENFORCE=FALSE

      - ENABLE_REPLICATION=FALSE
      - REPLICATION_CONFIG_SYNCPROV=binddn="cn=config" bindmethod=simple credentials="admin" searchbase="cn=config" type=refreshAndPersist retry="5 5 60 +" timeout=1 filter="(!(objectclass=olcGlobal))"
      - REPLICATION_DB_SYNCPROV=binddn="cn=admin,dc=example,dc=org" bindmethod=simple credentials="admin" searchbase="dc=example,dc=org" type=refreshAndPersist interval=00:00:00:10 retry="5 5 60 +" timeout=1
      - REPLICATION_HOSTS=ldap://ldap1.example.com ldap://ldap2.example.com ldap://ldap3.example.com
      - REMOVE_CONFIG_AFTER_SETUP=false

      - ENABLE_BACKUP=TRUE
      #- BACKUP_INTERVAL=0400
      #- BACKUP_RETENTION=10080
    networks:
      - services
    restart: always

networks:
  services:
    external: true


