#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-openldap
SERVICE_NAME="openldap-backup"
check_container_initialized
check_service_initialized init 10-openldap
liftoff

### Set Compression Options
if var_true "${BACKUP_PARALLEL_COMPRESSION}"; then
    bzip="pbzip2 -${BACKUP_COMPRESSION_LEVEL}"
    gzip="pigz -${BACKUP_COMPRESSION_LEVEL}"
    xzip="pixz -${BACKUP_COMPRESSION_LEVEL}"
    zstd="zstd --rm -${BACKUP_COMPRESSION_LEVEL}"
else
    bzip="bzip2 -${BACKUP_COMPRESSION_LEVEL}"
    gzip="gzip -${BACKUP_COMPRESSION_LEVEL}"
    xzip="xz -${BACKUP_COMPRESSION_LEVEL} "
    zstd="zstd --rm -${BACKUP_COMPRESSION_LEVEL}"
fi

backup_openldap() {
    print_notice "Backing up configuration schemas"
    target=config
    /usr/sbin/slapcat -F "${CONFIG_PATH}" -n 0  | silent tee "${BACKUP_TEMP_LOCATION}"/"${target}"
    exit_code=$?
    check_exit_code $target
    print_notice "Backing up user data"
    target=data
    /usr/sbin/slapcat -F "${CONFIG_PATH}" -n 1 | silent tee "${BACKUP_TEMP_LOCATION}"/"${target}"
    exit_code=$?
    check_exit_code $target
    target=${now}-openldap_${CONTAINER_NAME}
    compression
    generate_checksum
    move_backup
}

check_exit_code() {
    print_debug "OpenLDAP Backup Exit Code is ${exit_code}"
    case "${exit_code}" in
    0)
        print_info "OpenLDAP Backup of '${1}' completed successfully"
        ;;
    *)
        print_error "OpenLDAP Backup of '${1}' reported errors"
        master_exit_code=1
        ;;
    esac
}

compression() {
    case "${BACKUP_COMPRESSION,,}" in
    bz*)
        print_notice "Compressing backup with bzip2"
        target=${target}.tar.bz2
        tar --use-compress-program="${bzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data --transform "s|config|${now}-openldap_${CONTAINER_NAME}/config|" --transform "s|data|${now}-openldap_${CONTAINER_NAME}/data|"
        ;;
    gz*)
        print_notice "Compressing backup with gzip"
        target=${target}.tar.gz
        tar --use-compress-program="${gzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data --transform "s|config|${now}-openldap_${CONTAINER_NAME}/config|" --transform "s|data|${now}-openldap_${CONTAINER_NAME}/data|"
        ;;
    "none" | "false")
        target=${target}.tar
        tar -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data --transform "s|config|${now}-openldap_${CONTAINER_NAME}/config|" --transform "s|data|${now}-openldap_${CONTAINER_NAME}/data|"
        ;;
    xz*)
        print_notice "Compressing backup with xzip"
        target=${target}.tar.xz
        tar --use-compress-program="${xzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data --transform "s|config|${now}-openldap_${CONTAINER_NAME}/config|" --transform "s|data|${now}-openldap_${CONTAINER_NAME}/data|"
        ;;
    zst*)
        print_notice "Compressing backup with zstd"
        target=${target}.tar.zst
        tar --use-compress-program="${zstd} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data --transform "s|config|${now}-openldap_${CONTAINER_NAME}/config|" --transform "s|data|${now}-openldap_${CONTAINER_NAME}/data|"
        ;;
    esac
}

generate_checksum() {
    if var_true "${BACKUP_ENABLE_CHECKSUM}"; then
        if [ "${exit_code}" = "0" ]; then
            case "${BACKUP_CHECKSUM,,}" in
            "md5")
                checksum_command="md5sum"
                checksum_extension="md5"
                ;;
            sha*)
                checksum_command="sha1sum"
                checksum_extension="sha1"
                ;;
            esac

            print_notice "Generating ${checksum_extension^^} for '${target}'"
            cd "${BACKUP_TEMP_LOCATION}"
            ${checksum_command} "${target}" >"${target}"."${checksum_extension}"
            checksum_value=$(${checksum_command} "${target}" | awk ' { print $1}')
            print_debug "${checksum_extension^^}: ${checksum_value} - ${target}"
        else
            print_error "Skipping Checksum creation because backup did not complete successfully"
        fi
    fi
}

move_backup() {
    case "${BACKUP_SIZE_VALUE,,}" in
    "b" | "bytes")
        BACKUP_SIZE_VALUE=1
        ;;
    "[kK]" | "[kK][bB]" | "kilobytes" | "[mM]" | "[mM][bB]" | "megabytes")
        BACKUP_SIZE_VALUE="-h"
        ;;
    *)
        BACKUP_SIZE_VALUE=1
        ;;
    esac
    if [ "$BACKUP_SIZE_VALUE" = "1" ]; then
        FILESIZE="$(stat -c%s "${BACKUP_TEMP_LOCATION}"/"${target}")"
        print_notice "Backup of ${target} created with the size of ${FILESIZE} bytes"
    else
        FILESIZE=$(du -h "${BACKUP_TEMP_LOCATION}"/"${target}" | awk '{ print $1}')
        print_notice "Backup of ${target} created with the size of ${FILESIZE}"
    fi

    case "${BACKUP_TYPE,,}" in
        file* )
            mkdir -p "${BACKUP_PATH}"
            silent mv "${BACKUP_TEMP_LOCATION}"/*."${checksum_extension}" "${BACKUP_PATH}"/
            mv "${BACKUP_TEMP_LOCATION}"/"${target}" "${BACKUP_PATH}"/"${target}"
            if var_true "${BACKUP_CREATE_LATEST_SYMLINK}"; then
                ln -sf "${BACKUP_PATH}"/"${target}" "${BACKUP_PATH}"/latest-openldap_"${CONTAINER_NAME}"
            fi
            if [ -n "${BACKUP_ARCHIVE_TIME}" ]; then
                mkdir -p "${BACKUP_PATH_ARCHIVE}"
                find "${BACKUP_PATH}"/ -maxdepth 1 -mmin +"${BACKUP_ARCHIVE_TIME}" -iname "*" -exec mv {} "${BACKUP_PATH_ARCHIVE}" \;
            fi
        ;;
    esac
    rm -rf "${BACKUP_TEMP_LOCATION}"/config
    rm -rf "${BACKUP_TEMP_LOCATION}"/data
}

if [ "${MODE,,}" = "manual" ] || [ "${1,,}" = "manual" ] || [ "${1,,}" = "now" ]; then
    sleep 1
    BACKUP_BEGIN=+0
    manual=TRUE
    print_debug "Detected Manual Mode"
else
    sleep 5
    current_time=$(date +"%s")
    today=$(date +"%Y%m%d")
    if [[ $BACKUP_BEGIN =~ ^\+(.*)$ ]]; then
        waittime=$((${BASH_REMATCH[1]} * 60))
        target_time=$(($current_time + $waittime))
    else
        target_time=$(date --date="${today:0:4}-${today:4:2}-${today:6:2} ${BACKUP_BEGIN:0:2}:${BACKUP_BEGIN:2:2}" +"%s")
        if [[ "$target_time" < "$current_time" ]]; then
            target_time=$(($target_time + 24 * 60 * 60))
        fi
        waittime=$(($target_time - $current_time))
    fi

    print_debug "Wait Time: ${waittime} Target time: ${target_time} Current Time: ${current_time}"
    print_notice "Next Backup at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
    sleep ${waittime}
fi

while true; do
    mkdir -p "${BACKUP_TEMP_LOCATION}"
    backup_start_time=$(date +"%s")
    print_debug "Backup routines started time: $(date +'%Y-%m-%d %T %Z')"
    now=$(date +"%Y%m%d-%H%M%S")
    now_time=$(date +"%H:%M:%S")
    now_date=$(date +"%Y-%m-%d")
    backup_openldap
    backup_finish_time=$(date +"%s")
    backup_total_time=$(echo $((backup_finish_time - backup_start_time)))
    if [ -z "$master_exit_code" ]; then master_exit_code="0"; fi
    print_info "Backup routines finish time: $(date -d @${backup_finish_time} +"%Y-%m-%d %T %Z") with overall exit code ${master_exit_code}"
    print_notice "Backup routines time taken: $(echo ${backup_total_time} | awk '{printf "Hours: %d Minutes: %02d Seconds: %02d", $1/3600, ($1/60)%60, $1%60}')"

    if var_true "${CONTAINER_ENABLE_MONITORING}"; then
        case "${CONTAINER_MONITORING_BACKEND,,}" in
            zabbix )
                if binary_exists zabbix_sender; then
                    print_notice "Sending Backup Statistics to Zabbix"
                    silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k openldap.backup.size -o "$(stat -c%s "${BACKUP_PATH}"/"${target}")"
                    silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k openldap.backup.datetime -o "$(date -r "${BACKUP_PATH}"/"${target}" +'%s')"
                else
                    print_error "Zabbix Sender not detected. Cannot send backup statistics to Zabbix Server"
                    break
                fi
            ;;
        esac
    fi

    if [[ -n "${BACKUP_RETENTION}" ]]; then
        print_notice "Cleaning up old backups"
        find "${BACKUP_PATH}"/ -mmin +"${BACKUP_RETENTION}" -iname "*" -exec rm {} \;
    fi

    if [ -n "${POST_SCRIPT}" ]; then
        print_notice "Found POST_SCRIPT environment variable. Executing"
        eval "${POST_SCRIPT}"
    fi

    if var_true "${manual}"; then
        print_debug "Exiting due to manual mode"
        exit ${master_exit_code}
    else
        print_notice "Sleeping for another $(($BACKUP_INTERVAL * 60 - backup_total_time)) seconds. Waking up at $(date -d@"$(($(date +%s) + $(($BACKUP_INTERVAL * 60 - backup_total_time))))" +"%Y-%m-%d %T %Z") "
        sleep $(($BACKUP_INTERVAL * 60 - backup_total_time))
    fi
done
